server:
  port: 8001

spring:
  sql:
    init:
      platform: h2
  datasource:    
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver 
    username: sa
    password:

file:
  tempFileDir: c:\tmp

aws:
  sqs:
    queue:
      name: SampleQueue
    numberOfMessagesToPrefetch: 0      
    concurrency: 5
    sqslocal:    
      port: 18001
  s3:
    localfake:
#S3 Fake by local file system
#      type: file
#      baseDir: C:\tmp\objectstorage
#S3 Fake by s3rver    
      type: s3rver
      port: 4568
    bucket: mysd33bucket123
    
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    com.example: DEBUG   
    org.springframework.context.support.ResourceBundleMessageSource: ERROR     

api:
  backend:
    url: http://localhost:8000    
    
job002:
  chunkSize: 5    