apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-app
  name: batch-app
  labels:
    app.kubernetes.io/name: batch-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: batch-app  
  template:
    metadata:
      labels:
        app.kubernetes.io/name: batch-app
    spec:
      containers:
      - name: batch-app
        image: ${REPOSITORY_URI}:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        env:
        - name: ENV_TYPE
          value: production,log_container
        resources:
          requests:
            cpu: 0.25
            memory: 512Mi
          limits:
            cpu: 0.5
            memory: 1024Mi     